### ISSUE TITLE
Error on dark theme code...

### ISSUE THREAD

**Issue by Cyb3r7ron** [hadikachmar3/Udemy_Store_app#2]
Error on dark theme code...

Error: Expected  a value type of 'MaterialColor?', but got one of type 'Color.... please how can this be fixed???
![Screenshot 2021-11-18 121305](https://user-images.githubusercontent.com/45810961/142620414-af4938fe-81b3-4806-b63b-739471a55bad.png)
'

**Comment by hadikachmar3** [comment]
Hello, please post your code to be able to help you. 
Or you can compare it to my code.
