### ISSUE TITLE
Build Fail 

### ISSUE THREAD

**Issue by FarooqIT** [hadikachmar3/Udemy_Store_app#4]
**Very good work by @hadikachmar3 
Unfortunately I am getting Build Fail Error  here is the detail:**

`The plugin `stripe_payment` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib\main.dart on V2040 in debug mode...

**FAILURE: Build failed with an exception.**

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.grpc:grpc-core:[1.28.0].
     Required by:
         project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:23.0.0 > io.grpc:grpc-android:1.28.0
         project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:23.0.0 > io.grpc:grpc-okhttp:1.28.0
      > Failed to list versions for io.grpc:grpc-core.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.grpc:grpc-core:[1.28.0].
     Required by:
         project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:23.0.0 > io.grpc:grpc-android:1.28.0
         project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:23.0.0 > io.grpc:grpc-okhttp:1.28.0
      > Failed to list versions for io.grpc:grpc-core.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/io/grpc/grpc-core/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by hadikachmar3** [comment]
Hello Farooq,

Unfortunately this package has been deprecated, we should use another package, and all of them are similar. Try to use another package and lemme know if you need help

Best regards
Hadi

**Comment by FarooqIT** [comment]
Then which package should I use ?

**Comment by FarooqIT** [comment]
Secondly you did not explain where to give  _api-kay_,  _project url_, _database url_ of firestore in this flutter project **Udemy_Store_app**. Actually I am new to Flutter and Dart, I have been working in C#, Xamarin Forms.

**Comment by FarooqIT** [comment]
Waiting reply , 
**Anticipated Thanks**

**Comment by hadikachmar3** [comment]
> Secondly you did not explain where to give _api-kay_, _project url_, _database url_ of firestore in this flutter project **Udemy_Store_app**. Actually I am new to Flutter and Dart, I have been working in C#, Xamarin Forms.

I fully covered the Firebase firebase, firebase storage, and firebase auth, recheck the tutorials! And I gave the source code.

**Comment by hadikachmar3** [comment]
> Waiting reply , **Anticipated Thanks**

https://www.udemy.com/course/flutter-with-firebase-build-an-e-commerce-app-from-scratch/learn/#questions/16743500/

**Comment by FarooqIT** [comment]
Thanks a lot sir

**Comment by hadikachmar3** [comment]
I will close this issue now.
Feel free to reach me, and open a new issue if you have a problem, or reach us on discord https://discord.gg/MhnKaY5qdK

**Comment by FarooqIT** [comment]
Ok Sir I will contact you soon
