### ISSUE TITLE
The plugin `stripe_payment` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by harshpatel312** [hadikachmar3/Udemy_Store_app#6]
The plugin `stripe_payment` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib\main.dart on sdk gphone x86 in debug mode...

FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-android:{strictly 1.4.3}.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlinx:kotlinx-coroutines-android' that satisfies the version constraints:
           Dependency path 'android:app:unspecified' --> 'io.flutter.plugins.firebase.core:firebase_core:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-android:{strictly 1.4.3}' because of the following reason: debugRuntimeClasspath uses version 1.4.3

   > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2.
     Required by:
         project :app > androidx.window:window-java:1.0.0-beta04 > androidx.window:window:1.0.0-beta04
      > Cannot find a version of 'org.jetbrains.kotlinx:kotlinx-coroutines-android' that satisfies the version constraints:
           Dependency path 'android:app:unspecified' --> 'io.flutter.plugins.firebase.core:firebase_core:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'
           Constraint path 'android:app:unspecified' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-android:{strictly 1.4.3}' because of the following reason: debugRuntimeClasspath uses version 1.4.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by hadikachmar3** [comment]
Hello,

Watch this tutorial 
https://youtu.be/BR4sF_VzV0w
I am going to close this for now, feel free to open it at any time!
